[features]
seeds = true
skip-lint = false
[programs.localnet]
origin_validation = "7n4AUGyiAbCwv3F6GKyJAPAS9KCbDb3QKYsgHcPCPnFP"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/Users/mikebrown/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
